### ISSUE TITLE
Notify nodeserver of a thread crash error, and try to restart?

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-poly-hue-emu#3]
```
2019-11-25 07:35:03,073 [Thread-1  ] [ERROR] ISY Could not recieve response from device because of a network issue.
2019-11-25 07:35:13,099 [Thread-1  ] [ERROR] Timed out waiting for response from the ISY device.
2019-11-25 07:35:23,281 [Thread-1  ] [ERROR] Timed out waiting for response from the ISY device.
2019-11-25 07:35:33,300 [Thread-1  ] [ERROR] Timed out waiting for response from the ISY device.
2019-11-25 07:35:43,319 [Thread-1  ] [ERROR] Timed out waiting for response from the ISY device.
2019-11-25 07:35:53,351 [Thread-1  ] [ERROR] Timed out waiting for response from the ISY device.
2019-11-25 07:36:03,375 [Thread-1  ] [ERROR] ISY Could not recieve response from device because of a network issue.
2019-11-25 07:36:03,386 [Thread-1  ] [ERROR] ISY Could not parse variables, poorly formatted XML.
2019-11-25 07:36:03,407 [Thread-1  ] [ERROR] Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./hue-emu-poly.py", line 135, in _connect
    self.thread = Thread(target=self.isy_hue_emu.connect(listen))
  File "/home/pi/development/udi-poly-hue-emu/ISYHueEmulator.py", line 45, in connect
    self.isy = PyISY.ISY(self.isy_host, self.isy_port, self.isy_user, self.isy_password, False, "1.1", LOGGER)
  File "PyISY/PyISY/ISY.py", line 88, in __init__
    if self.configuration['Weather Information']:
KeyError: 'Weather Information'
```

**Comment by jimboca** [comment]
Should be fixed now.
